### ISSUE TITLE
Integrate TeXify

### ISSUE THREAD

**Issue by aashutoshrathi** [Hsankesara/Draughts-AI#1]
The README file contains equations (important ofc) which are necessary but the Markdown can't have it all.

We miss the ![](https://latex.codecogs.com/svg.latex?\LaTeX)

## Proposed Solution

1. Use SVG using arguments in URL. (as I used to render LaTeX above)
**For eg:** `https://latex.codecogs.com/svg.latex?\text{42}` renders ![](https://latex.codecogs.com/svg.latex?\text{42})

2. Integrate [TeXify](https://github.com/apps/texify)
This app takes `.tex.md` files and compile them into MD with equations :sparkles:

I hope this helps. 😁
You can payback for my time by helping me in similar domain projects 😉

**Comment by Hsankesara** [comment]
Thank you. Will add it ASAP.

**Comment by piyush-pawar-17** [comment]
@aashutoshrathi No.

**Comment by Hsankesara** [comment]
I added latex integration. Thank you @aashutoshrathi for your guidance.

**Comment by piyush-pawar-17** [comment]
@aashutoshrathi All Stack Developer for a reason.
